name: CI

on:
  push:
    branches: "main"
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "22.x"
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint

  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "22.x"
          cache: pnpm
      - run: pnpm install
      - run: pnpm check
