name: Deploy to GitHub Pages

on:
  push:
    branches: "main"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: pnpm
        run: |
          pnpm install

      - env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: |
          pnpm build

      - uses: actions/upload-pages-artifact@v2
        with:
          # this should match the `pages` option in your adapter-static options
          path: "build/"

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
